language: objective-c

notifications:
  email:
    on_success: never
    on_failure: change

before_script:
  - pushd $HOME
  - mkdir -p go
  - export GOPATH="$HOME/go"
  - export PATH=$PATH:$GOPATH/bin
  - go version
  - go get -u github.com/golang/lint/golint
  - go get -u golang.org/x/tools/cmd/cover
  - go get -u golang.org/x/tools/cmd/goimports
  - go get -u golang.org/x/tools/cmd/vet
  - go get -u sourcegraph.com/sqs/goreturns
  - popd

script:
  - 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'
