version: "{build}"

platform: x64

branches:
  only:
    - master

skip_tags: true

environment:
  GOPATH: c:\gopath
  GOVERSION: 1.7
  APM_TEST_PACKAGES: environment go-config go-get autocomplete-go gofmt navigator-go tester-go gorename gometalinter-linter linter builder-go go-debug godoc
  ATOM_LINT_WITH_BUNDLED_NODE: "false"

  matrix:
  - ATOM_CHANNEL: stable
  - ATOM_CHANNEL: beta

install:
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - rmdir c:\go /s /q
  - appveyor DownloadFile https://storage.googleapis.com/golang/go%GOVERSION%.windows-amd64.zip
  - 7z x go%GOVERSION%.windows-amd64.zip -y -oC:\ > NUL
  - go version
  - go env
  - mkdir c:\gopath
  - go get -u golang.org/x/tools/cmd/cover
  - go get -u golang.org/x/tools/cmd/goimports
  - go get -u sourcegraph.com/sqs/goreturns
  - go get -u github.com/rogpeppe/godef
  - go get -u github.com/nsf/gocode
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter --install --update
  - ps: Install-Product node 6

build_script:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/atom/ci/943a16cd32926bdfcca703f16ec6a958a2db38a5/build-package.ps1'))

test: off
deploy: off
