version: "{build}"

platform: x64

branches:
  only:
    - master
    - /^greenkeeper-.*$/

skip_tags: true

environment:
  GOPATH: c:\gopath
  GOVERSION: 1.9
  APM_TEST_PACKAGES: linter go-signature-statusbar go-debug hyperclick

  matrix:
  - ATOM_CHANNEL: stable
  - ATOM_CHANNEL: beta

install:
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - rmdir c:\go /s /q
  - appveyor DownloadFile https://storage.googleapis.com/golang/go%GOVERSION%.windows-amd64.zip
  - 7z x go%GOVERSION%.windows-amd64.zip -y -oC:\ > NUL
  - go version
  - go env
  - mkdir c:\gopath
  - go get -u golang.org/x/tools/cmd/goimports
  - go get -u golang.org/x/tools/cmd/gorename
  - go get -u github.com/sqs/goreturns
  - go get -u github.com/mdempsky/gocode
  - go get -u github.com/alecthomas/gometalinter
  - go get -u github.com/zmb3/gogetdoc
  - go get -u github.com/zmb3/goaddimport
  - go get -u github.com/rogpeppe/godef
  - go get -u github.com/fatih/gomodifytags
  - go get -u golang.org/x/tools/cmd/guru
  - go get -u github.com/tpng/gopkgs

build_script:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/atom/ci/master/build-package.ps1'))

test: off
deploy: off
